project:
  type: website
  output-dir: docs

website:
  title: "Angelina — Portfolio"
  navbar:
    left:
      - text: About You
        href: about.qmd
      - text: Projects
        href: projects.qmd
      - text: Contact
        href: contact.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
